theme: jekyll-theme-cayman
title: Home Office DDaT Playbook
description:
baseurl: "/playbook" # the subpath of your site, e.g. /blog
# baseurl: "" # the subpath of your site, e.g. /blog - use for dev
excerpt_separator: "<!--more-->"
breadcrumbs:
  root:
    hide: true  # show breadcrumbs on root/home page
    image: false # Show image or title text
show_downloads: false
sass:
    sass_dir: _sass
google_analytics: UA-100424158-2
permalink: pretty

collections: 
  playbooks:
    output: true
  user-centereds:
    output: true
  homeworkings:
    output: true
  
